version: '3'

services:
  app:
    image: 'spring-docker-fable:latest'
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fable
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: fable
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  postgres:
    image: 'postgres:13'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fable
      POSTGRES_DB: fable
  test:
    image: 'test'
    container_name: test
    build: ./test
    depends_on:
      - app
    entrypoint: [ "sh", "-c", "python test.py" ]